/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface Card {
  Id?: number;
  SetId: number;
  WordType: string;
  Kanji: string;
  Furigana: string;
  Answer: string;
  CardOwner: string;
}
export interface CardsWordtype {
  WordType: string;
}
export interface KanjiCard {
  Id?: number;
  SetId: number;
  Kanji: string;
  Onyomi: string;
  Kunyomi: string;
  English: string;
  CardOwner: string;
}
export interface Set {
  Id: number;
  SetName: string;
  SetOwner: string;
  SupersetId: number | null;
  CardType?: string | null;
}
export interface Stat {
  CardId: number;
  KanjiCardId: number | null;
  StatOwner: string;
  Correct?: number | null;
  Incorrect?: number | null;
}
export interface Superset {
  Id: number;
  SupersetName: string | null;
  SupersetDescription: string | null;
  SupersetOwner: string;
}
export interface SessionToken {
  Username: string;
  SessionNonce: string;
  BestBefore: Date;
}
export interface User {
  Username: string;
  HashedPassword: string;
}
