/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface Card {
  Id: number;
  SetId: number | null;
  WordType: number | null;
  Kanji: string;
  Furigana: string;
  CardOwner: string | null;
}
export interface Cardswordtype {
  Id: number;
  Noun: any;
  RuVerb: any;
  UVerb: any;
  IrregularVerb: any;
  Transitive: any;
  Intransitive: any;
  Other: any;
  NaAdjective: any;
  IAdjective: any;
  SpecialKuruVerb: any;
  SpecialSuruVerb: any;
  SpecialAruVerb: any;
}
export interface Englishdefinition {
  Definition: string | null;
  CardId: number | null;
  Owner: string | null;
}
export interface Set {
  Id: number;
  SetName: string;
  SetOwner: string | null;
  SupersetId: number | null;
  CardType: string | null;
}
export interface Stat {
  CardId: number;
  StatOwner: string;
  Correct?: number;
  Incorrect?: number;
}
export interface Superset {
  Id?: number;
  SupersetName: string;
  SupersetDescription: string | null;
  SupersetOwner: string | null;
}
export interface User {
  Id: string;
}
