/*
 * This used to be the old backend model before the sql server was lost.
 * Keeping for documentation purposes
 */

/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface User {
  Username: string;
  HashedPassword: string;
}
export interface SessionToken {
  Username: string;
  SessionNonce: string;
  BestBefore: Date;
}
export interface Superset {
  Id: number;
  SupersetName: string | null;
  SupersetDescription: string | null;
  SupersetOwner: string;
}
export interface Set {
  Id: number;
  SetName: string;
  SetOwner: string;
  SupersetId: number | null;
  CardType?: string | null;
}
export interface CardsWordtype {
  Id: number;
  Noun?: any | null;
  RuVerb?: any | null;
  UVerb?: any | null;
  IrregularVerb?: any | null;
  Transitive?: any | null;
  Intransitive?: any | null;
  Other?: any | null;
  NaAdjective?: any | null;
  IAdjective?: any | null;
  SpecialKuruVerb?: any | null;
  SpecialSuruVerb?: any | null;
  SpecialAruVerb?: any | null;
}
export interface Card {
  Id?: number;
  SetId: number;
  WordType: number | null;
  Kanji: string;
  Furigana: string;
  Answer: string;
  CardOwner: string;
}
export interface KanjiCard {
  Id?: number;
  SetId: number;
  Kanji: string;
  Onyomi: string;
  Kunyomi: string;
  English: string;
  CardOwner: string;
}
export interface Stat {
  CardId: number;
  KanjiCardId: number | null;
  StatOwner: string;
  Correct?: number | null;
  Incorrect?: number | null;
}
